coverage:
  status:
    project:
      default:
        target: auto
        base: auto
        threshold: 1
ignore:
  - "src/api/lib/tasks/dev/"
comment:
  layout: "reach, diff, flags"
  require_changes: true
