inherits_from: .haml-lint_todo.yml

require:
  - './lib/haml-lint/custom_linters/set_pagetitle_in_view.rb'

linters:
  LineLength:
    max: 150

  # Apply lint in all partials, but exclude 'breadcrumb_items' partials
  InstanceVariables:
    enabled: true
    file_types: not_breadcrumb_items
    matchers:
      not_breadcrumb_items: \A_(?!breadcrumb_items).*\.haml\z

  SetPagetitleInView:
    enabled: true
    exclude:
      - 'app/views/webui/users/new.html.haml'

exclude:
- 'vendor/bundle/**/*'
